-- Create ACTIVITY table
CREATE TABLE ACTIVITY (
    ACTIVITY_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    ACTIVITY_TYPE VARCHAR(50) NOT NULL,
    ACTION VARCHAR(400) NOT NULL,
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);