-- Create P2P_SETUP table
CREATE TABLE P2P_SETUP (
    P2P_SETUP_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    STATUS VARCHAR(50),
    LEND_AMOUNT INT,
    REMAINING_AMOUNT INT,
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);