-- Create P2P_TRANSACTION table
CREATE TABLE P2P_TRANSACTION (
    P2P_TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    LEND_AMOUNT INT,
    MERCHANT_ID INT,
    STATUS VARCHAR(50),
    SETTLEMENT_DATE INT,
    PAID_AMOUNT INT,
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (MERCHANT_ID) REFERENCES P2P_SETUP(USER_ID)
);