-- Create BANK_ACCOUNT_DETAILS table
CREATE TABLE BANK_ACCOUNT_DETAILS (
    BANK_ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    BANK_ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
    BANK_NAME VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USER_ID INT
);