-- Create USER_EXPENSES_GROUP table
CREATE TABLE USER_EXPENSES_GROUP (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    GROUP_ID INT,
    JOIN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES EXPENSES_GROUP(GROUP_ID)
);