-- Create EXPENSES_DETAILS table
CREATE TABLE EXPENSES_DETAILS (
    DETAILS_ID INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    ITEM_NAME VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY INT,
    UPDATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    GROUP_ID INT,
    FOREIGN KEY (GROUP_ID) REFERENCES EXPENSES_GROUP(GROUP_ID)
);